backend_photo_biography_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:index" }

backend_photo_biography_show:
    path:     /{id}/show
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:show" }

backend_photo_biography_new:
    path:     /new
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:new" }

backend_photo_biography_create:
    path:     /create
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:create" }
    methods:  POST

backend_photo_biography_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:edit" }

backend_photo_biography_update:
    path:     /{id}/update
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:update" }
    methods:  [POST, PUT]

backend_photo_biography_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteMainBundle:Backend/PhotoBiography:delete" }
    methods:  [POST, DELETE]
