frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_feedback:
    path:     /feedback
    defaults: { _controller: "SiteMainBundle:Frontend/Main:feedback" }

frontend_callback:
    path:     /callback
    defaults: { _controller: "SiteMainBundle:Frontend/Main:callback" }

frontend_media:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/media.yml"
    prefix: /miedia

frontend_products:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/products.yml"
    prefix: /products

frontend_element:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/element.yml"
    prefix: /elements

frontend_our_work_element:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/our_work_element.yml"
    prefix: /our_work_elements

frontend_portfolio:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/portfolio.yml"
    prefix: /portfolio

frontend_page:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/page.yml"
    prefix: /