frontend_our_work_element_one:
    path:     /{permalink}/our_work_element/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Products:one" }
    requirements:
      permalink: .+

frontend_element_one:
    path:     /{permalink}/element/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Products:one" }
    requirements:
      permalink: .+

frontend_products_one:
    path:     /{permalink}
    defaults: { _controller: "SiteMainBundle:Frontend/Products:one", slug: null }
    requirements:
      permalink: .+

