<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function findAllWithoutParent(){
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT p FROM SiteMainBundle:Products p
            WHERE p.parent IS NULL
        ');

        return $query->getResult();
    }
}
