<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    /**
     * Продукты в левом меню
     * @return array
     */
    public function findAllWithoutParent(){
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT p FROM SiteMainBundle:Products p
            WHERE p.parent IS NULL
            ORDER BY p.position ASC
        ');

        return $query->getResult();
    }

    /**
     * Продукты на главной
     *
     * @return array
     */
    public function findAllWithoutParentOnMain(){
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT p FROM SiteMainBundle:Products p
            WHERE p.parent IS NULL
            AND p.main = 1
            ORDER BY p.position ASC
        ');

        return $query->getResult();
    }
}
